### PR TITLE
Mark repository private until March 29, 2022 when picoCTF 2022 is over

### PR DESCRIPTION
**Pull request by hiliang-cmu**
We would greatly appreciate folks refrain from public posting write-ups until the competition is over

### CODE REVIEW

**Comment by hiliang-cmu** [comment]
@ssahillppatell

**Comment by ssahillppatell** [comment]
@hiliang-cmu Hey made it private a day back. I only realised it was public when someone forked. Sorry for that 🥲. Really sorry

**Comment by hiliang-cmu** [comment]
Ah, I guess you can't private while I have a fork, and I have a fork because I couldn't submit an issue only a PR.

I'll delete my fork now

Thank you

**Comment by ssahillppatell** [comment]
@hiliang-cmu Actually. I created the repo on my account. Then I saw someone(@Emmanuel-kwizera ) fork it. Realizing my mistake, I made the repo private on my account. Now the repo remains in @Emmanuel-kwizera's account only

**Comment by hiliang-cmu** [comment]
Ohh, I see. So we need to get @Emmanuel-kwizera to shut this one down.

**Pull request closed without merging**
